### ISSUE TITLE
[Bug] Rule34hentai suddenly not working?

### ISSUE THREAD

**Issue by Daydayalltheway** [NO-ob/LoliSnatcher_Droid#78]
Can't add the site now for some reason, entered the API even though its not entirely necessary. Doesn't work with no configuration either. No favorites from this site load either. Any help?

**Comment by Dabu-dot** [comment]
Rule34Hentai.net seems to be under Internal Server issues for several hours now. I would suggest to wait and progressively see if you can regain access to the website (no HTTP 500 Error, no report on server, successful loads of images and videos) before retrying to load the config into Lolisnatcher.

**Comment by Daydayalltheway** [comment]
So I have regained access to the site, images videos on the site and favorites in lolisnatcher are loading, but I still can't add the site to the booru list. Any suggestions? Thanks in advance :)

**Comment by RequiemXN** [comment]
![1](https://user-images.githubusercontent.com/66484393/147853129-145d1978-05de-43eb-800b-5e50923dad43.jpg)
![2](https://user-images.githubusercontent.com/66484393/147853170-52fa3dde-ad2d-4f70-9208-abe40ea720b1.PNG)
What am I doing wrong? The choice of autodetect and r34hentai in booru type did not change the result.

**Comment by NANI-SORE** [comment]
Seems like they removed their api, I'll see later if it was just moved to different url or completely removed.
![image](https://user-images.githubusercontent.com/12685712/147853463-9a68445d-7dd2-4944-9cbd-f650dbe132ee.png)

**Comment by NANI-SORE** [comment]
They really did remove the api, so I will convert our handler to parse html instead in the next release

P.S. @RequiemXN why are you still on pre-2.0 version?

**Comment by RequiemXN** [comment]
> so I will convert our handler to parse html instead in the next release

In that case, when can we expect the next release?
 > P.S. @RequiemXN why are you still on pre-2.0 version?

I have already updated, thanks for the advice.

**Comment by NANI-SORE** [comment]
Sometimes during next week probably, there is some changes and features I need to finish and test before we'll do a release

**Comment by NANI-SORE** [comment]
Fixed in 2.1.0, along with gelbooru that broke today.
We will wait a few days before we push an in-app notification about the update, since we don't want to annoy play store users until update hits the store

**Comment by RequiemXN** [comment]
Thank you, the problem is partially resolved. Now, if it doesn't make it difficult, can you answer?
Do you need to get cookies under one IP from USA for restricted tags? When logging in from a pc, cookies are not suitable for android? Each device has a different VPN.

**Comment by NANI-SORE** [comment]
Yes, the session token is based on IP and site stops accepting it when session IP and your current IP don't match

**Comment by RequiemXN** [comment]
Yes, it is decided, for residents of other countries where access to this site is prohibited, a USA proxy is needed. Otherwise, as I understand it, the site simply does not allow authorization through the parser. Although it is strange that the PC had a completely different IP, it did not affect and the tags showed up. Sorry for my translator language)

**Comment by NANI-SORE** [comment]
Без проблем, закрой тему если больше нет претензий
